
export type User = {
  employeeType: string,
  givenName: string,
  sn: string,
  id: string,
  isActive: boolean,
  challengeSetTimestamp: string,
  // idautoDisabled: boolean,
  idautoPersonRenameFlagDate: string,
  idautoPersonRenameUsername: string,
  idautoPersonClaimFlag: boolean,
  identifier: string,
  mail: string,
  passwordLastSet: string,
};

export type RIUser = {
  employeeType: string,
  givenName: string,
  id: string,
  idautoChallengeSetTimestamp: string,
  idautoDisabled: boolean,
  idautoPersonClaimFlag: string,
  idautoPersonHRID: number|null,
  idautoPersonRenameFlagDate: string,
  idautoPersonRenameUsername: string,
  idautoPersonStuID: string|null,
  mail: string,
  passwordLastSet: string,
  sn: string,
};

type UserDetailAttribute = {
  name: string,
  ri: string | undefined,
  hr: string | undefined,
  sis: string | undefined,
  ad: string | undefined,
  azure: string | undefined,
  google: string | undefined,
}

export type UserDetails = {
  id: string,
  isClaimed: boolean,
  photoURL?: string,
  system: UserDetailAttribute[],
  demographics: UserDetailAttribute[],
  position: UserDetailAttribute[],
  contact: UserDetailAttribute[],
};

export type RIUserDetails = {
  active: string,
  createTimestamp: string,
  displayName: string,
  employeeType: string,
  givenName: string,
  hr: string,
  id: string,
  idautoPasswordLastModified: string,
  idautoPersonActivationDate: string,
  idautoPersonBirthdate: string,
  idautoPersonClaimCode: string,
  idautoPersonClaimFlag: string,
  idautoPersonCourseCodes: string,
  idautoPersonDeptDescr: string,
  idautoDisabled: string,
  idautoLocked: boolean,
  idautoPersonExt4: string,
  idautoPersonExt5: string,
  idautoPersonExt6: string,
  idautoPersonExt7: string,
  idautoPersonExt8: string,
  idautoPersonExt9: string,
  idautoPersonExt12: string,
  idautoPersonExtBool2: string,
  idautoPersonGender: string,
  idautoPersonHomeEmail: string,
  idautoPersonHRID: string,
  idautoPersonJobCode: string,
  idautoPersonJobTitle: string,
  idautoPersonLocCodes: string,
  idautoPersonLocNames: string,
  idautoPersonPhotoURL: string | undefined,
  idautoPersonRenameFlagDate: string,
  idautoPersonRenameUsername: string,
  idautoPersonSAMAccountName: string,
  idautoPersonSchoolCodes: string,
  idautoPersonSchoolNames: string,
  idautoPersonSourceStatus: string,
  idautoPersonStuID: string,
  idautoPersonSystem3ID: string,
  idautoPersonSystem4ID: string,
  idautoPersonUserNameMV: string,
  isActive: boolean,
  mail: string,
  mobile: string,
  modifiersName: string,
  modifyTimestamp: string,
  pwdChangedTime: string,
  pwdReset: string,
  sis: string,
  sn: string,
};